title: Random Linear Coding
tagline: [Federated Learning over Wireless Multiple Access Channels]
baseurl: "/FederatedLearning-RLC"
markdown: kramdown

# About/contact
author:
  name:       Afshin Abdi
  url:        https://afshinabdi.github.io
